"""
Voyage AI embedding helper.

Provides a thin wrapper around langchain-voyageai to generate query-time
embeddings.  Document-side embeddings are handled server-side by Atlas
AutoEmbeddings (autoEmbed vector index with voyage-4-large).

The same VoyageAIEmbeddings instance is re-used by the vector store and
search retrievers so that query-time embeddings match the document-time
embeddings generated by Atlas.
"""

from functools import lru_cache

from langchain_voyageai import VoyageAIEmbeddings

from config.settings import VOYAGE_API_KEY, AUTO_EMBEDDING_MODEL


@lru_cache(maxsize=1)
def get_voyage_embeddings() -> VoyageAIEmbeddings:
    """Return a cached VoyageAIEmbeddings instance using voyage-4-large."""
    if not VOYAGE_API_KEY:
        raise ValueError("VOYAGE_API_KEY is not set. Check your .env file.")
    return VoyageAIEmbeddings(
        voyage_api_key=VOYAGE_API_KEY,
        model=AUTO_EMBEDDING_MODEL,
    )


def generate_embedding(text: str) -> list[float]:
    """Generate a single embedding vector for *text*."""
    model = get_voyage_embeddings()
    return model.embed_query(text)


def generate_embeddings(texts: list[str]) -> list[list[float]]:
    """Batch-generate embeddings for a list of texts."""
    model = get_voyage_embeddings()
    return model.embed_documents(texts)
